### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by markjfine** [markjfine/nrsc5-dui#2]
- [ ] 1. I've been fooling around with the app on Linux as well and seems like it's doing what it's supposed to do. I'd really like to start cleaning up the code style and make it look closer to 2.0... given time. I also need to try it in my Windows  VM, but that may be a reach.
- [ ] 2. I'm a little disappointed in some of these stations' sloppy implementation. Naming a stream MPS/SPS1/SPS2 is pretty lazy. Think I'll write something that looks in the bookmarks and uses the name in there as an alternative.
- [ ] 3. Right now, the stations broadcast logos for each stream, but the app only applies it to the logo list if you're tuned to it when it's received. I understand the reasoning for that, but think it should be applied when received whether you're turned to the stream or not.
- [ ] 4. Also thinking about redesigning the Album Art tab to look more like how a car radio might actually look. Maybe split the area into a line at the top that shows the station call and small image of the logo in the upper right (or to the right of where I have the call showing now), a couple of small lines at the bottom that show the slogan and message, and then flash the covers as they come in the center between them. Some don't have covers, so that would be a larger static version of the logo. If I find a way to do it, I'll put the slogan and message on one line, and make it crawl across the bottom.
- [ ] 5. I want to research how Navteq/HERE works and see what can be done with it. Seems like another source of info in case an iHeart station isn't available. There are other digital services that are used that can also be taken advantage of.
- [ ] 6. Kind of a minor nit: I have no idea why they left the timestamp off the traffic maps. That thing could be five days old and you'd never know it. At the least I'll add the timestamp, or have something on there that displays the dtg that the file was saved so it doesn't obscure part of the map.
- [ ] 7. I'd like to modify nrsc5 to work with my AirSpy HF Discovery, maybe my first priority. The RTL-SDR is a nice toy, and it does a lot of things, but there are a lot of problems trying to use it for something like this. There are a lot of other stations that I'm sure an AirSpy would be able to pick up that are otherwise getting washed out on an RTL-SDR. I put a feeler out to see if anything's being done to use other receivers, but that kind of fell flat.
- [ ] 8. Add standard FM Stereo with RDS and AM with C-QUAM.
